sudo: required
dist: trusty
language: c

compiler:
    - gcc
    - clang

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - libtool
            - m4

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew update ; brew install openmpi ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get -qq update ; sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551 ; sudo apt-get -qq install openmpi-bin libopenmpi-dev ; fi

script:
    - ./autogen.sh && ./configure
    - make -j 8
    - cd test ; mkdir /tmp/test ; HIO_TEST_ROOTS=posix:/tmp/test make check
